name       : sidewinderd
version    : 0.4.1
release    : 2
source     :
    - https://github.com/tolga9009/sidewinderd/archive/0.4.1.tar.gz : 7d1de22f249cc4f456861164674484ca25e05832e887684616c56c2a7254e33f
license    : MIT
component  : desktop
summary    : Linux support for Microsoft SideWinder X4 / X6 and Logitech G105 / G710+.
description: This project provides support for gaming peripherals under Linux. It was originally designed for the Microsoft SideWinder X4, but the developers have extended support for more keyboards. Their goal is to create a framework-like environment for rapid driver development under Linux.
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(tinyxml2)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install

