name       : sidewinderd
version    : 0.4.2
release    : 4
source     :
    - https://github.com/tolga9009/sidewinderd/archive/0.4.2.tar.gz : 4f79b92118ff5c5da0c093439bf875079f5243e852ecc769888d7d5a53cff62e
license    : MIT
component  : desktop
summary    : Linux support for Microsoft SideWinder X4 / X6 and Logitech G105 / G710+.
description: |
    This project provides support for gaming peripherals under Linux. It was originally designed for the Microsoft SideWinder X4, but the developers have extended support for more keyboards. Their goal is to create a framework-like environment for rapid driver development under Linux.
builddeps  :
    - pkgconfig(libconfig)
    - pkgconfig(tinyxml2)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
